### ISSUE TITLE
MSB3774	Could not find SDK "Microsoft.VCLibs, Version=14.0"

### ISSUE THREAD

**Issue by bitbonk** [thomasclaudiushuber/Uwp-Visual-Studio-Shell#1]
When I try to build this I get this error: 
>Error	MSB3774	Could not find SDK "Microsoft.VCLibs, Version=14.0".	TreeViewControl	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	2049	

I guess something is missing on my machine, but it is not obvious to me what it is and how to get it.

**Comment by bitbonk** [comment]
It worked in VS2017 RC.

**Comment by thomasclaudiushuber** [comment]
Hi bitbonk, thanks for the update. Great it works now for you
